language: objective-c
osx_image: xcode10.2

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage

install:
- cd QLog
- bundle install

script:
- bundle exec fastlane test

after_success:
- bash <(curl -s https://codecov.io/bash)
